////////////////////////////////////////////////////
// This is an AutoGenerated class created by Rocketlane for its Salesforce integration
// DO NOT EDIT OR DELETE THIS CLASS
////////////////////////////////////////////////////



trigger RLSTAGEWH394ACCOUNT on Account (after insert, after update, after delete, after undelete) {

    try {


    RLSTAGEWH394.TriggerContext tc = new RLSTAGEWH394.TriggerContext(
        Account.sObjectType,
        Trigger.isExecuting,
        Trigger.isInsert,
        Trigger.isUpdate,
        Trigger.isDelete,
        Trigger.isUndelete,
        Trigger.isBefore,
        Trigger.isAfter,
        Trigger.new,
        Trigger.newMap,
        Trigger.old,
        Trigger.oldMap,
        Trigger.size);

    List<String> fieldsToFetchChildRecordsFor = new List<String> {  };
    List<String> fieldsBeingListenedForUpdates = new List<String> { 'Vitally_CSM__c','AWS_Region__c','ARR__c','Data_Warehouse__c','Customer_Tier__c','Customer_Instance_URL__c' };
    RLSTAGEWH394 webhookPusher = new RLSTAGEWH394(tc, fieldsToFetchChildRecordsFor, fieldsBeingListenedForUpdates);

    System.debug('RLSTAGEWH394ACCOUNT - Processing records');

    if (Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
         System.debug('RLSTAGEWH394ACCOUNT - Queueing');
         System.enqueueJob(webhookPusher);
    }
    else {
        System.debug('RLSTAGEWH394ACCOUNT - Queue limit reached for transaction');
    }

    }
    catch(Exception e) {
        System.debug('Exception when handling trigger: ' + e.getMessage());
        System.debug(e.getStackTraceString());
    }

}