////////////////////////////////////////////////////
// This is an AutoGenerated class created by Rocketlane for its Salesforce integration
// DO NOT EDIT OR DELETE THIS CLASS
////////////////////////////////////////////////////



trigger RLSTAGEWH394OPPORTUNITY on Opportunity (after insert, after update, after delete, after undelete) {

    try {


    RLSTAGEWH394.TriggerContext tc = new RLSTAGEWH394.TriggerContext(
        Opportunity.sObjectType,
        Trigger.isExecuting,
        Trigger.isInsert,
        Trigger.isUpdate,
        Trigger.isDelete,
        Trigger.isUndelete,
        Trigger.isBefore,
        Trigger.isAfter,
        Trigger.new,
        Trigger.newMap,
        Trigger.old,
        Trigger.oldMap,
        Trigger.size);

    List<String> fieldsToFetchChildRecordsFor = new List<String> { 'AccountId','Technical_Owner__c','OwnerId' };
    List<String> fieldsBeingListenedForUpdates = new List<String> { 'AccountId.Name','Trial_Next_Steps__c','AccountId','OwnerId.Name','Days_in_Current_POC_Stage__c','Amount','POC_Stage__c','AccountId.Data_Warehouse__c','CloseDate','Technical_Owner__c.Email','OwnerId','Atlan_Entity__c','AccountId.AWS_Region__c','POC_Eng_Asks__c','AccountId.Customer_Instance_URL__c','Blocker_Details__c' };
    RLSTAGEWH394 webhookPusher = new RLSTAGEWH394(tc, fieldsToFetchChildRecordsFor, fieldsBeingListenedForUpdates);

    System.debug('RLSTAGEWH394OPPORTUNITY - Processing records');

    if (Limits.getQueueableJobs() < Limits.getLimitQueueableJobs()) {
         System.debug('RLSTAGEWH394OPPORTUNITY - Queueing');
         System.enqueueJob(webhookPusher);
    }
    else {
        System.debug('RLSTAGEWH394OPPORTUNITY - Queue limit reached for transaction');
    }

    }
    catch(Exception e) {
        System.debug('Exception when handling trigger: ' + e.getMessage());
        System.debug(e.getStackTraceString());
    }

}